version: "2"
services:
  prestashop:
    image: prestashop/prestashop:1.5.6.2
    ports:
      - 4000:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./public:/var/www/html
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=alien_prestashop
      - PS_INSTALL_AUTO=0
  mysql:
    image: mysql:5.6
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 2000:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
